version: "3"

services:
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    command: go run main.go
    expose:
      - 18081
      - 18082
    volumes:
      - ./backend:/go/src/github.com/ryoshindo/envoy-catchup/rewrite/backend

  envoy:
    image: envoyproxy/envoy:v1.25-latest
    command:
      - /usr/local/bin/envoy
      - --config-path /etc/envoy/config.yml
    ports:
      - 8081:8081
      - 8082:8082
      - 9901:9901
    volumes:
      - ./envoy:/etc/envoy
